name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
            version: 9
      - run: pnpm install
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 3.3.3
          prettier_options: --check src
          prettier_plugins: '@trivago/prettier-plugin-sort-imports prettier-plugin-tailwindcss'
